# Generated by Django 4.1.6 on 2024-04-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BSE', 'BSE'), ('CBSE', 'CBSE'), ('Competitive', 'Competitive')], max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
