# Generated by Django 4.1.6 on 2024-04-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_coursefee_duration_coursefee_qualification_and_more'),
        ('institute_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.coursefee'),
        ),
    ]
