# Generated by Django 4.1.6 on 2024-04-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_panel', '0002_student_course_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_fee',
        ),
    ]
