# Generated by Django 4.1.6 on 2024-04-16 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('institute_panel', '0003_remove_student_course_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
