# Generated by Django 4.1.1 on 2024-04-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_coursefee_duration_coursefee_qualification_and_more'),
        ('institute_panel', '0005_student_course_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.IntegerField(choices=[(0, 'Payement Pending'), (1, 'Payement Success')], default=0)),
                ('course_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.coursefee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_panel.student')),
            ],
        ),
    ]
