# Generated by Django 4.1.1 on 2024-04-17 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_panel', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute_panel.student'),
        ),
    ]
