# Generated by Django 4.1.6 on 2024-04-18 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('institute_panel', '0009_remove_payment_amount_remove_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Payment Pending'), (1, 'Payment Success')], default=0),
        ),
    ]
