# Generated by Django 4.1.6 on 2024-04-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_panel', '0011_alter_payment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute_panel.student'),
        ),
    ]
