# Generated by Django 4.1.6 on 2024-04-18 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_coursefee_duration_coursefee_qualification_and_more'),
        ('institute_panel', '0012_alter_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.institute'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_panel.student'),
        ),
    ]
