# Generated by Django 4.1.6 on 2024-04-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_panel', '0013_payment_institute_alter_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
